# Tensorflow Introduction

Tensorflow is one of the widely used libraries for implementing Machine learning and other algorithms involving large number of mathematical operations. Tensorflow was developed by Google and it’s one of the most popular Machine Learning libraries on GitHub.

In [13]:
import tensorflow as tf
import numpy as np

TensorFlow, as the name indicates, is a framework to define and run computations involving tensors. A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

### tf.Tensor

A tf.Tensor object represents a partially defined computation that will eventually produce a value. TensorFlow programs work by first building a graph of tf.Tensor objects, detailing how each tensor is computed based on the other available tensors and then by running parts of this graph to achieve the desired results.

A tf.Tensor has the following properties:
1. a data type(float32, int32, string)
2. a shape

Some types of tensors are:
* tf.Varibale
* tf.constant
* tf.placeholder
* tf.SparseTensor

### Print Hello world 

### tf.constant

Creates a constant tensor.

The resulting tensor is populated with values of type dtype, as specified by arguments value and (optionally) shape

In [6]:
msg = tf.constant("Hello World")
t1 = tf.constant([1,2,3,4,5,6,7])
t2 = tf.constant(-2, shape=[2,3])
t3 = tf.constant(4)

### tf.Session

A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

In [7]:
#start session
sess = tf.Session()
print(sess.run(msg))
print(sess.run(t1))
print(sess.run(t2))
print(sess.run(t3))
#close session
sess.close()

b'Hello World'
[1 2 3 4 5 6 7]
[[-2 -2 -2]
 [-2 -2 -2]]
4


### Basic Operations

In [4]:
a = tf.constant(2)
b = tf.constant(3)

In [5]:
with tf.Session() as sess:
    print("a: %i"% sess.run(a), "b: %i" %sess.run(b))
    print("Addition: ",sess.run(a+b))
    print("Multiplication: ",sess.run(a*b))

a: 2 b: 3
Addition:  5
Multiplication:  6


### tf.placeholder 

Inserts a placeholder for a tensor that will be always fed.
A placeholder is simply a variable that will assign data to at a later date.

In [20]:
x = tf.placeholder(tf.float32, shape=(3,3))
y = tf.matmul(x,x)

In [21]:
with tf.Session() as sess:
    #print(sess.run(y))    will fail because x was not fed
    rand_array = np.random.rand(3,3)
    print(sess.run(y, feed_dict={x: rand_array}))

[[0.7347388  0.7813669  0.54605985]
 [0.6552819  1.0428407  0.9772979 ]
 [1.2315404  1.2146521  1.044431  ]]


In [22]:
c = tf.placeholder(tf.int16)
d = tf.placeholder(tf.int16)

In [23]:
add = tf.add(c,d)
mul = tf.multiply(c,d)

In [24]:
with tf.Session() as sess:
    print("Addition: ", sess.run(add, feed_dict={c:2, d:5}))
    print("Multiplication: ", sess.run(mul, feed_dict={c:2, d:5}))

Addition:  7
Multiplication:  10


### Matrix Multiplication

In [29]:
# Create Constant that produces a 1 x 2 matrix
m1 = tf.constant([[3., 3.]])
# Create Constant that produces a 2 x 1 matrix
m2 = tf.constant([[2.],[2.]])

### tf.matmul

Multiplies matrix m1 by matrix m2, producing m1 * m2.

Both matrices must be of the same type. The supported types are: float16, float32, float64, int32, complex64, complex128.

*tf.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    name=None
)*

In [26]:
product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    print("Result: ",sess.run(product))

Result:  [[12.]]


Either matrix can be transposed or adjointed (conjugated and transposed) on the fly by setting one of the corresponding flag to True. These are False by default.

In [28]:
# Create two constants that produces a 3 x 1 matrix
a = tf.constant([[1],[2],[3]])
b = tf.constant([[4],[5],[6]])
mul = tf.matmul(a,b, transpose_a = True)   # transpose matrix a
with tf.Session() as sess:
    print("Result: ",sess.run(mul))

Result:  [[32]]


If one or both of the matrices contain a lot of zeros, a more efficient multiplication algorithm can be used by setting the corresponding a_is_sparse or b_is_sparse flag to True. These are False by default.

In [30]:
a = tf.constant([1,2,3,4,5,6], shape=[2,3])
b = tf.constant([7,8,0,0,0,0], shape=[3,2])
c = tf.matmul(a,b, b_is_sparse=True)
with tf.Session() as sess:
    print("Result: ",sess.run(c))

Result:  [[ 7  8]
 [28 32]]


### tf.argmax

Returns the index with the largest value across axes of a tensor. 

*tf.argmax(
    input,
    axis=None,
    name=None,
    dimension=None,
    output_type=tf.int64
)*

In [38]:
a = tf.constant([34,5,66,84,23,46,75,33,67], shape=[3,3])
argmx = tf.argmax(a)
with tf.Session() as sess:
    print(sess.run(a))
    print("Index of largest value across axes: ",sess.run(argmx))

[[34  5 66]
 [84 23 46]
 [75 33 67]]
Index of largest value across axes:  [1 2 2]


### tf.argmin

Returns the index with the smallest value across axes of a tensor.

*tf.argmin(
    input,
    axis=None,
    name=None,
    dimension=None,
    output_type=tf.int64
)*

In [37]:
argmn = tf.argmin(a)
with tf.Session() as sess:
    print(sess.run(a))
    print("Index of smallest value across axes: ",sess.run(argmn))

[[34  5 66]
 [84 23 46]
 [75 33 67]]
Index of smallest value across axes:  [0 0 1]


### tf.equal

Returns the truth value of (x == y) element-wise.

*tf.equal(
    x,
    y,
    name=None
)*

In [43]:
a = tf.constant([1,8,3,4,5,6], shape=[2,3])
b = tf.constant([7,8,0,5,5,6], shape=[2,3])
equal = tf.equal(a,b)
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(equal))

[[1 8 3]
 [4 5 6]]
[[False  True False]
 [False  True  True]]


### tf.reduce_mean

Computes the mean of elements across dimensions of a tensor.

*tf.reduce_mean(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None,
    reduction_indices=None,
    keep_dims=None
)*

In [53]:
x = tf.constant([[1., 1.],[2., 2.]])
mean = tf.reduce_mean(x)    # overall mean
mean1 = tf.reduce_mean(x,0)    # mean over column
mean2 = tf.reduce_mean(x,1)    # mean over row
with tf.Session() as sess:
    print(sess.run(mean))
    print('Column:')
    print(sess.run(mean1))
    print('Row')
    print(sess.run(mean2))

1.5
Column:
[1.5 1.5]
Row
[1. 2.]
