In [1]:
import tensorflow as tf
import numpy as np

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


## tf.enable_eager_execution

Enables eager execution for the lifetime of this program.

With eager execution enabled, TensorFlow functions execute operations immediately as opposed to adding to a graph to be executed later in a tf.Session and return concrete values as opposed to symbolic references to a node in a computational graph.

*tf.enable_eager_execution(
    config=None,
    device_policy=None,
    execution_mode=None
)*

In [2]:
#set eager api
tf.enable_eager_execution()
tfe = tf.contrib.eager

#### Running without tf.Session

In [3]:
tf.multiply(6,7).numpy()

42

In [4]:
#Define constant tensors
a = tf.constant(2)
b = tf.constant(3)
print("a: %i" % a)
print("b: %i" % b)

a: 2
b: 3


In [5]:
# run operation
c = a + b
print("Add: %i" %c)
d = a * b
print("Multiply: %i" %d)

Add: 5
Multiply: 6


In [6]:
#Tensors and numpy arrays
m1 = tf.constant([[2.,1.], [1.,0.]], dtype= tf.float32)
m2 = np.array([[3.,0.],[5.,1.]], dtype = np.float32)
print("Tensor a = \n %s" %m1)
print("Numpy array b =\n %s" %m2)

Tensor a = 
 tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
Numpy array b =
 [[3. 0.]
 [5. 1.]]


In [7]:
# matrix addition
m_add = m1 + m2
print(m_add)

tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)


In [8]:
# matrix multiplication
m_mul = tf.matmul(m1,m2)
print(m_mul)

tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [13]:
a = tf.constant([34,5,66,84,23,46,75,33,67], shape=[3,3])
a_max = tf.argmax(a)
print("Index of largest values accross axes: %s" %a_max)

Index of largest values accross axes: tf.Tensor([1 2 2], shape=(3,), dtype=int64)


In [14]:
a_min = tf.argmin(a)
print("Index of smallest values accross axes: %s" %a_min)

Index of smallest values accross axes: tf.Tensor([0 0 1], shape=(3,), dtype=int64)
